###
POST http://localhost:9000/api/ventas HTTP/1.1
Content-Type: application/json

{
    "tamaño": "grande",
    "total": 100000,
    "cantidad de productos": 15,
    "mensaje": "gracias por su compra vuelva pronto"
}

###
GET http://localhost:9000/api/ventas HTTP/1.1

###
GET http://localhost:9000/api/ventas/637ab8b010bcaa077c5a7805 HTTP/1.1

###
PUT http://localhost:9000/api/ventas/637ab8b010bcaa077c5a7805 HTTP/1.1
Content-Type: application/json

{
    "tamaño": "pequeño",
    "total": 30000,
    "mensaje": "gracias por su compra vuelva pronto"
}

###
DELETE http://localhost:9000/api/ventas/637ab8b010bcaa077c5a7805 HTTP/1.1